// GENERATED by build-regex-pack.js from exclude-pack.txt — do not edit by hand.
// 12 rules, all verified to compile.
window.UNVIX_EXCLUDE_PACK = [
  "\\.(png|jpe?g|gif|svg|webp|avif|bmp|ico)($|\\?)",
  "\\.(css|scss|sass|less)($|\\?)",
  "\\.(woff2?|ttf|otf|eot)($|\\?)",
  "\\.map($|\\?)",
  "\\.(mp4|webm|mov|mp3|wav|ogg|pdf|zip|gz|tar|7z)($|\\?)",
  "/(assets?|dist|build|public|_next|static)/([^/?#]+/)*[^/?#]+\\.(js|mjs|json|txt|xml|yml|yaml|csv)($|\\?)",
  "node_modules/",
  "^/(favicon\\.ico|robots\\.txt|sitemap\\.xml|manifest\\.json|browserconfig\\.xml|service-worker\\.js|sw\\.js|workbox-[^/]*\\.js)($|\\?)",
  "^https?://(cdn|cdnjs|unpkg|jsdelivr|fonts)\\.",
  "^/(@vite|@react-refresh|__vite|__webpack|hot-update)",
  "^/(health|healthz|readyz|livez|ping|status|metrics)($|[/?])",
  "[.-][0-9a-f]{8,}\\.(js|css|png|jpe?g|svg|woff2?)($|\\?)"
];
